// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DTest: typeof import('./../components/custom/DTest.vue')['default']
    HelloWorld: typeof import('./../components/custom/HelloWorld.vue')['default']
    IconCustomNo1: typeof import('~icons/custom/no1')['default']
    IconEpEdit: typeof import('~icons/ep/edit')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
